// Code generated by cmd/protoschema (-lang swift). DO NOT EDIT.
// Regenerate with `make mac-models` after changing internal/protocol.
//
// These types mirror the vix daemon⇄client wire protocol
// (internal/protocol). They decode the `data` payload of a ThreadEvent
// and encode the `data` of a ThreadCommand.

import Foundation

public struct Attachment: Codable, Sendable, Equatable {
    public var data: String
    public var mediaType: String
    public var path: String?
    public var type: String

    public init(data: String, mediaType: String, path: String? = nil, type: String) {
        self.data = data
        self.mediaType = mediaType
        self.path = path
        self.type = type
    }

    enum CodingKeys: String, CodingKey {
        case data = "data"
        case mediaType = "media_type"
        case path = "path"
        case type = "type"
    }
}

public struct DirUsage: Codable, Sendable, Equatable {
    public var count: Int64
    public var lastRequestAt: String?
    public var path: String

    public init(count: Int64, lastRequestAt: String? = nil, path: String) {
        self.count = count
        self.lastRequestAt = lastRequestAt
        self.path = path
    }

    enum CodingKeys: String, CodingKey {
        case count = "count"
        case lastRequestAt = "last_request_at"
        case path = "path"
    }
}

public struct EventCompacted: Codable, Sendable, Equatable {
    public var auto: Bool
    public var fromTokens: Int64
    public var summarizedTurns: Int64
    public var toTokens: Int64

    public init(auto: Bool, fromTokens: Int64, summarizedTurns: Int64, toTokens: Int64) {
        self.auto = auto
        self.fromTokens = fromTokens
        self.summarizedTurns = summarizedTurns
        self.toTokens = toTokens
    }

    enum CodingKeys: String, CodingKey {
        case auto = "auto"
        case fromTokens = "from_tokens"
        case summarizedTurns = "summarized_turns"
        case toTokens = "to_tokens"
    }
}

public struct EventConfirmRequest: Codable, Sendable, Equatable {
    public var detail: String?
    public var params: [String: JSONValue]
    public var requestedDirs: [String]?
    public var toolName: String

    public init(detail: String? = nil, params: [String: JSONValue], requestedDirs: [String]? = nil, toolName: String) {
        self.detail = detail
        self.params = params
        self.requestedDirs = requestedDirs
        self.toolName = toolName
    }

    enum CodingKeys: String, CodingKey {
        case detail = "detail"
        case params = "params"
        case requestedDirs = "requested_dirs"
        case toolName = "tool_name"
    }
}

public struct EventError: Codable, Sendable, Equatable {
    public var code: String?
    public var message: String

    public init(code: String? = nil, message: String) {
        self.code = code
        self.message = message
    }

    enum CodingKeys: String, CodingKey {
        case code = "code"
        case message = "message"
    }
}

public struct EventInitState: Codable, Sendable, Equatable {
    public var model: String?
    public var state: Int64

    public init(model: String? = nil, state: Int64) {
        self.model = model
        self.state = state
    }

    enum CodingKeys: String, CodingKey {
        case model = "model"
        case state = "state"
    }
}

public struct EventJobDone: Codable, Sendable, Equatable {
    public var error: String?
    public var jobId: String
    public var name: String?
    public var status: String
    public var threadId: String?

    public init(error: String? = nil, jobId: String, name: String? = nil, status: String, threadId: String? = nil) {
        self.error = error
        self.jobId = jobId
        self.name = name
        self.status = status
        self.threadId = threadId
    }

    enum CodingKeys: String, CodingKey {
        case error = "error"
        case jobId = "job_id"
        case name = "name"
        case status = "status"
        case threadId = "thread_id"
    }
}

public struct EventJobRun: Codable, Sendable, Equatable {
    public var error: String?
    public var jobId: String
    public var name: String?
    public var status: String

    public init(error: String? = nil, jobId: String, name: String? = nil, status: String) {
        self.error = error
        self.jobId = jobId
        self.name = name
        self.status = status
    }

    enum CodingKeys: String, CodingKey {
        case error = "error"
        case jobId = "job_id"
        case name = "name"
        case status = "status"
    }
}

public struct EventJobsChanged: Codable, Sendable, Equatable {

    public init() {
    }
}

public struct EventMCPChanged: Codable, Sendable, Equatable {

    public init() {
    }
}

public struct EventPlanComplete: Codable, Sendable, Equatable {
    public var plan: Plan

    public init(plan: Plan) {
        self.plan = plan
    }

    enum CodingKeys: String, CodingKey {
        case plan = "plan"
    }
}

public struct EventPlanProposed: Codable, Sendable, Equatable {
    public var plan: Plan

    public init(plan: Plan) {
        self.plan = plan
    }

    enum CodingKeys: String, CodingKey {
        case plan = "plan"
    }
}

public struct EventPlanTaskDone: Codable, Sendable, Equatable {
    public var success: Bool
    public var summary: String
    public var taskIdx: Int64
    public var title: String

    public init(success: Bool, summary: String, taskIdx: Int64, title: String) {
        self.success = success
        self.summary = summary
        self.taskIdx = taskIdx
        self.title = title
    }

    enum CodingKeys: String, CodingKey {
        case success = "success"
        case summary = "summary"
        case taskIdx = "task_idx"
        case title = "title"
    }
}

public struct EventPlanTaskStart: Codable, Sendable, Equatable {
    public var taskIdx: Int64
    public var title: String
    public var total: Int64

    public init(taskIdx: Int64, title: String, total: Int64) {
        self.taskIdx = taskIdx
        self.title = title
        self.total = total
    }

    enum CodingKeys: String, CodingKey {
        case taskIdx = "task_idx"
        case title = "title"
        case total = "total"
    }
}

public struct EventQuestionOption: Codable, Sendable, Equatable {
    public var description: String
    public var hasUserInput: Bool?
    public var title: String

    public init(description: String, hasUserInput: Bool? = nil, title: String) {
        self.description = description
        self.hasUserInput = hasUserInput
        self.title = title
    }

    enum CodingKeys: String, CodingKey {
        case description = "description"
        case hasUserInput = "has_user_input"
        case title = "title"
    }
}

public struct EventReplay: Codable, Sendable, Equatable {
    public var activePlan: Plan?
    public var activeWorkflow: String?
    public var initializing: Bool?
    public var messages: [ReplayMessage]
    public var model: String?
    public var threadMode: String?
    public var title: String?
    public var todos: [TodoItem]?
    public var warnings: [String]?

    public init(activePlan: Plan? = nil, activeWorkflow: String? = nil, initializing: Bool? = nil, messages: [ReplayMessage], model: String? = nil, threadMode: String? = nil, title: String? = nil, todos: [TodoItem]? = nil, warnings: [String]? = nil) {
        self.activePlan = activePlan
        self.activeWorkflow = activeWorkflow
        self.initializing = initializing
        self.messages = messages
        self.model = model
        self.threadMode = threadMode
        self.title = title
        self.todos = todos
        self.warnings = warnings
    }

    enum CodingKeys: String, CodingKey {
        case activePlan = "active_plan"
        case activeWorkflow = "active_workflow"
        case initializing = "initializing"
        case messages = "messages"
        case model = "model"
        case threadMode = "thread_mode"
        case title = "title"
        case todos = "todos"
        case warnings = "warnings"
    }
}

public struct EventReplayReady: Codable, Sendable, Equatable {
    public var activeWorkflow: String?
    public var model: String?
    public var threadMode: String?
    public var warnings: [String]?

    public init(activeWorkflow: String? = nil, model: String? = nil, threadMode: String? = nil, warnings: [String]? = nil) {
        self.activeWorkflow = activeWorkflow
        self.model = model
        self.threadMode = threadMode
        self.warnings = warnings
    }

    enum CodingKeys: String, CodingKey {
        case activeWorkflow = "active_workflow"
        case model = "model"
        case threadMode = "thread_mode"
        case warnings = "warnings"
    }
}

public struct EventRetry: Codable, Sendable, Equatable {
    public var attempt: Int64
    public var maxRetries: Int64
    public var reason: String
    public var waitSecs: Int64

    public init(attempt: Int64, maxRetries: Int64, reason: String, waitSecs: Int64) {
        self.attempt = attempt
        self.maxRetries = maxRetries
        self.reason = reason
        self.waitSecs = waitSecs
    }

    enum CodingKeys: String, CodingKey {
        case attempt = "attempt"
        case maxRetries = "max_retries"
        case reason = "reason"
        case waitSecs = "wait_secs"
    }
}

public struct EventSkillsAvailable: Codable, Sendable, Equatable {
    public var skills: [SkillInfo]

    public init(skills: [SkillInfo]) {
        self.skills = skills
    }

    enum CodingKeys: String, CodingKey {
        case skills = "skills"
    }
}

public struct EventStreamChunk: Codable, Sendable, Equatable {
    public var text: String

    public init(text: String) {
        self.text = text
    }

    enum CodingKeys: String, CodingKey {
        case text = "text"
    }
}

public struct EventStreamDone: Codable, Sendable, Equatable {
    public var cacheCreationTokens: Int64
    public var cacheReadTokens: Int64
    public var elapsedMs: Int64
    public var inputTokens: Int64
    public var outputTokens: Int64

    public init(cacheCreationTokens: Int64, cacheReadTokens: Int64, elapsedMs: Int64, inputTokens: Int64, outputTokens: Int64) {
        self.cacheCreationTokens = cacheCreationTokens
        self.cacheReadTokens = cacheReadTokens
        self.elapsedMs = elapsedMs
        self.inputTokens = inputTokens
        self.outputTokens = outputTokens
    }

    enum CodingKeys: String, CodingKey {
        case cacheCreationTokens = "cache_creation_tokens"
        case cacheReadTokens = "cache_read_tokens"
        case elapsedMs = "elapsed_ms"
        case inputTokens = "input_tokens"
        case outputTokens = "output_tokens"
    }
}

public struct EventThinkingChunk: Codable, Sendable, Equatable {
    public var text: String

    public init(text: String) {
        self.text = text
    }

    enum CodingKeys: String, CodingKey {
        case text = "text"
    }
}

public struct EventThinkingStall: Codable, Sendable, Equatable {
    public var elapsedMs: Int64
    public var summaryChars: Int64

    public init(elapsedMs: Int64, summaryChars: Int64) {
        self.elapsedMs = elapsedMs
        self.summaryChars = summaryChars
    }

    enum CodingKeys: String, CodingKey {
        case elapsedMs = "elapsed_ms"
        case summaryChars = "summary_chars"
    }
}

public struct EventThreadStarted: Codable, Sendable, Equatable {
    public var forkTurnIdx: Int64?
    public var parentId: String?
    public var startedAt: String
    public var threadId: String
    public var whiteboardBase: String?

    public init(forkTurnIdx: Int64? = nil, parentId: String? = nil, startedAt: String, threadId: String, whiteboardBase: String? = nil) {
        self.forkTurnIdx = forkTurnIdx
        self.parentId = parentId
        self.startedAt = startedAt
        self.threadId = threadId
        self.whiteboardBase = whiteboardBase
    }

    enum CodingKeys: String, CodingKey {
        case forkTurnIdx = "fork_turn_idx"
        case parentId = "parent_id"
        case startedAt = "started_at"
        case threadId = "thread_id"
        case whiteboardBase = "whiteboard_base"
    }
}

public struct EventThreadsChanged: Codable, Sendable, Equatable {

    public init() {
    }
}

public struct EventTitleUpdated: Codable, Sendable, Equatable {
    public var title: String

    public init(title: String) {
        self.title = title
    }

    enum CodingKeys: String, CodingKey {
        case title = "title"
    }
}

public struct EventTodoListUpdated: Codable, Sendable, Equatable {
    public var todos: [TodoItem]

    public init(todos: [TodoItem]) {
        self.todos = todos
    }

    enum CodingKeys: String, CodingKey {
        case todos = "todos"
    }
}

public struct EventToolBackends: Codable, Sendable, Equatable {
    public var globConfigured: String
    public var globEffective: String
    public var grepConfigured: String
    public var grepEffective: String

    public init(globConfigured: String, globEffective: String, grepConfigured: String, grepEffective: String) {
        self.globConfigured = globConfigured
        self.globEffective = globEffective
        self.grepConfigured = grepConfigured
        self.grepEffective = grepEffective
    }

    enum CodingKeys: String, CodingKey {
        case globConfigured = "glob_configured"
        case globEffective = "glob_effective"
        case grepConfigured = "grep_configured"
        case grepEffective = "grep_effective"
    }
}

public struct EventToolCall: Codable, Sendable, Equatable {
    public var arguments: [String: JSONValue]?
    public var name: String
    public var reason: String?
    public var reasonNotEditFile: String?
    public var reasonNotGlobFiles: String?
    public var reasonNotReadFile: String?
    public var reasonToIncreaseTimeout: String?
    public var summary: String
    public var timeoutSec: Int64?
    public var toolId: String

    public init(arguments: [String: JSONValue]? = nil, name: String, reason: String? = nil, reasonNotEditFile: String? = nil, reasonNotGlobFiles: String? = nil, reasonNotReadFile: String? = nil, reasonToIncreaseTimeout: String? = nil, summary: String, timeoutSec: Int64? = nil, toolId: String) {
        self.arguments = arguments
        self.name = name
        self.reason = reason
        self.reasonNotEditFile = reasonNotEditFile
        self.reasonNotGlobFiles = reasonNotGlobFiles
        self.reasonNotReadFile = reasonNotReadFile
        self.reasonToIncreaseTimeout = reasonToIncreaseTimeout
        self.summary = summary
        self.timeoutSec = timeoutSec
        self.toolId = toolId
    }

    enum CodingKeys: String, CodingKey {
        case arguments = "arguments"
        case name = "name"
        case reason = "reason"
        case reasonNotEditFile = "reason_not_edit_file"
        case reasonNotGlobFiles = "reason_not_glob_files"
        case reasonNotReadFile = "reason_not_read_file"
        case reasonToIncreaseTimeout = "reason_to_increase_timeout"
        case summary = "summary"
        case timeoutSec = "timeout_sec"
        case toolId = "tool_id"
    }
}

public struct EventToolResult: Codable, Sendable, Equatable {
    public var detail: String?
    public var isError: Bool
    public var name: String
    public var output: String
    public var toolId: String

    public init(detail: String? = nil, isError: Bool, name: String, output: String, toolId: String) {
        self.detail = detail
        self.isError = isError
        self.name = name
        self.output = output
        self.toolId = toolId
    }

    enum CodingKeys: String, CodingKey {
        case detail = "detail"
        case isError = "is_error"
        case name = "name"
        case output = "output"
        case toolId = "tool_id"
    }
}

public struct EventUpdateAvailable: Codable, Sendable, Equatable {
    public var current: String
    public var latest: String?
    public var method: String?
    public var url: String?

    public init(current: String, latest: String? = nil, method: String? = nil, url: String? = nil) {
        self.current = current
        self.latest = latest
        self.method = method
        self.url = url
    }

    enum CodingKeys: String, CodingKey {
        case current = "current"
        case latest = "latest"
        case method = "method"
        case url = "url"
    }
}

public struct EventUserQuestion: Codable, Sendable, Equatable {
    public var category: String?
    public var options: [String]
    public var placeholder: String?
    public var question: String
    public var questions: [QuestionDef]?
    public var richOptions: [EventQuestionOption]?

    public init(category: String? = nil, options: [String], placeholder: String? = nil, question: String, questions: [QuestionDef]? = nil, richOptions: [EventQuestionOption]? = nil) {
        self.category = category
        self.options = options
        self.placeholder = placeholder
        self.question = question
        self.questions = questions
        self.richOptions = richOptions
    }

    enum CodingKeys: String, CodingKey {
        case category = "category"
        case options = "options"
        case placeholder = "placeholder"
        case question = "question"
        case questions = "questions"
        case richOptions = "rich_options"
    }
}

public struct EventWorkflowComplete: Codable, Sendable, Equatable {
    public var durationMs: Int64?
    public var stepCosts: [StepCost]?
    public var success: Bool
    public var summary: String?
    public var workflowName: String

    public init(durationMs: Int64? = nil, stepCosts: [StepCost]? = nil, success: Bool, summary: String? = nil, workflowName: String) {
        self.durationMs = durationMs
        self.stepCosts = stepCosts
        self.success = success
        self.summary = summary
        self.workflowName = workflowName
    }

    enum CodingKeys: String, CodingKey {
        case durationMs = "duration_ms"
        case stepCosts = "step_costs"
        case success = "success"
        case summary = "summary"
        case workflowName = "workflow_name"
    }
}

public struct EventWorkflowStart: Codable, Sendable, Equatable {
    public var steps: [WorkflowStepInfo]?
    public var totalSteps: Int64
    public var workflowName: String

    public init(steps: [WorkflowStepInfo]? = nil, totalSteps: Int64, workflowName: String) {
        self.steps = steps
        self.totalSteps = totalSteps
        self.workflowName = workflowName
    }

    enum CodingKeys: String, CodingKey {
        case steps = "steps"
        case totalSteps = "total_steps"
        case workflowName = "workflow_name"
    }
}

public struct EventWorkflowStatus: Codable, Sendable, Equatable {
    public var elapsedSeconds: Int64?
    public var iteration: Int64?
    public var note: String?
    public var status: String
    public var stepId: String?
    public var tokenBudget: Int64?
    public var tokensUsed: Int64?
    public var workflowName: String

    public init(elapsedSeconds: Int64? = nil, iteration: Int64? = nil, note: String? = nil, status: String, stepId: String? = nil, tokenBudget: Int64? = nil, tokensUsed: Int64? = nil, workflowName: String) {
        self.elapsedSeconds = elapsedSeconds
        self.iteration = iteration
        self.note = note
        self.status = status
        self.stepId = stepId
        self.tokenBudget = tokenBudget
        self.tokensUsed = tokensUsed
        self.workflowName = workflowName
    }

    enum CodingKeys: String, CodingKey {
        case elapsedSeconds = "elapsed_seconds"
        case iteration = "iteration"
        case note = "note"
        case status = "status"
        case stepId = "step_id"
        case tokenBudget = "token_budget"
        case tokensUsed = "tokens_used"
        case workflowName = "workflow_name"
    }
}

public struct EventWorkflowStepDone: Codable, Sendable, Equatable {
    public var bashOutput: String?
    public var cacheCreationTokens: Int64?
    public var cacheReadTokens: Int64?
    public var command: String?
    public var display: String?
    public var durationMs: Int64?
    public var inputTokens: Int64?
    public var model: String?
    public var outputTokens: Int64?
    public var stepId: String
    public var stepIdx: Int64
    public var success: Bool
    public var timedOut: Bool?
    public var toolStats: [ToolStat]?
    public var total: Int64

    public init(bashOutput: String? = nil, cacheCreationTokens: Int64? = nil, cacheReadTokens: Int64? = nil, command: String? = nil, display: String? = nil, durationMs: Int64? = nil, inputTokens: Int64? = nil, model: String? = nil, outputTokens: Int64? = nil, stepId: String, stepIdx: Int64, success: Bool, timedOut: Bool? = nil, toolStats: [ToolStat]? = nil, total: Int64) {
        self.bashOutput = bashOutput
        self.cacheCreationTokens = cacheCreationTokens
        self.cacheReadTokens = cacheReadTokens
        self.command = command
        self.display = display
        self.durationMs = durationMs
        self.inputTokens = inputTokens
        self.model = model
        self.outputTokens = outputTokens
        self.stepId = stepId
        self.stepIdx = stepIdx
        self.success = success
        self.timedOut = timedOut
        self.toolStats = toolStats
        self.total = total
    }

    enum CodingKeys: String, CodingKey {
        case bashOutput = "bash_output"
        case cacheCreationTokens = "cache_creation_tokens"
        case cacheReadTokens = "cache_read_tokens"
        case command = "command"
        case display = "display"
        case durationMs = "duration_ms"
        case inputTokens = "input_tokens"
        case model = "model"
        case outputTokens = "output_tokens"
        case stepId = "step_id"
        case stepIdx = "step_idx"
        case success = "success"
        case timedOut = "timed_out"
        case toolStats = "tool_stats"
        case total = "total"
    }
}

public struct EventWorkflowStepStart: Codable, Sendable, Equatable {
    public var agent: String
    public var explanation: String?
    public var stepId: String
    public var stepIdx: Int64
    public var total: Int64

    public init(agent: String, explanation: String? = nil, stepId: String, stepIdx: Int64, total: Int64) {
        self.agent = agent
        self.explanation = explanation
        self.stepId = stepId
        self.stepIdx = stepIdx
        self.total = total
    }

    enum CodingKeys: String, CodingKey {
        case agent = "agent"
        case explanation = "explanation"
        case stepId = "step_id"
        case stepIdx = "step_idx"
        case total = "total"
    }
}

public struct EventWorkflowsAvailable: Codable, Sendable, Equatable {
    public var workflows: [WorkflowInfo]

    public init(workflows: [WorkflowInfo]) {
        self.workflows = workflows
    }

    enum CodingKeys: String, CodingKey {
        case workflows = "workflows"
    }
}

public struct HookSummary: Codable, Sendable, Equatable {
    public var createdBy: String?
    public var enabled: Bool
    public var event: String?
    public var id: String
    public var lastFiredAt: String?
    public var lastStatus: String?
    public var matcher: String?
    public var mode: String?
    public var name: String?

    public init(createdBy: String? = nil, enabled: Bool, event: String? = nil, id: String, lastFiredAt: String? = nil, lastStatus: String? = nil, matcher: String? = nil, mode: String? = nil, name: String? = nil) {
        self.createdBy = createdBy
        self.enabled = enabled
        self.event = event
        self.id = id
        self.lastFiredAt = lastFiredAt
        self.lastStatus = lastStatus
        self.matcher = matcher
        self.mode = mode
        self.name = name
    }

    enum CodingKeys: String, CodingKey {
        case createdBy = "created_by"
        case enabled = "enabled"
        case event = "event"
        case id = "id"
        case lastFiredAt = "last_fired_at"
        case lastStatus = "last_status"
        case matcher = "matcher"
        case mode = "mode"
        case name = "name"
    }
}

public struct InstanceRegisterData: Codable, Sendable, Equatable {
    public var instanceId: String?
    public var mode: String?

    public init(instanceId: String? = nil, mode: String? = nil) {
        self.instanceId = instanceId
        self.mode = mode
    }

    enum CodingKeys: String, CodingKey {
        case instanceId = "instance_id"
        case mode = "mode"
    }
}

public struct JobSummary: Codable, Sendable, Equatable {
    public var createdBy: String?
    public var enabled: Bool
    public var id: String
    public var lastRunAt: String?
    public var lastStatus: String?
    public var name: String?
    public var nextRunAt: String?
    public var recentErrorCount: Int64?
    public var recentRunCount: Int64?
    public var running: Bool?
    public var schedule: String?
    public var triggerType: String?

    public init(createdBy: String? = nil, enabled: Bool, id: String, lastRunAt: String? = nil, lastStatus: String? = nil, name: String? = nil, nextRunAt: String? = nil, recentErrorCount: Int64? = nil, recentRunCount: Int64? = nil, running: Bool? = nil, schedule: String? = nil, triggerType: String? = nil) {
        self.createdBy = createdBy
        self.enabled = enabled
        self.id = id
        self.lastRunAt = lastRunAt
        self.lastStatus = lastStatus
        self.name = name
        self.nextRunAt = nextRunAt
        self.recentErrorCount = recentErrorCount
        self.recentRunCount = recentRunCount
        self.running = running
        self.schedule = schedule
        self.triggerType = triggerType
    }

    enum CodingKeys: String, CodingKey {
        case createdBy = "created_by"
        case enabled = "enabled"
        case id = "id"
        case lastRunAt = "last_run_at"
        case lastStatus = "last_status"
        case name = "name"
        case nextRunAt = "next_run_at"
        case recentErrorCount = "recent_error_count"
        case recentRunCount = "recent_run_count"
        case running = "running"
        case schedule = "schedule"
        case triggerType = "trigger_type"
    }
}

public struct MCPServerSummary: Codable, Sendable, Equatable {
    public var auth: String?
    public var enabled: Bool
    public var error: String?
    public var name: String
    public var status: String
    public var toolCount: Int64
    public var type: String

    public init(auth: String? = nil, enabled: Bool, error: String? = nil, name: String, status: String, toolCount: Int64, type: String) {
        self.auth = auth
        self.enabled = enabled
        self.error = error
        self.name = name
        self.status = status
        self.toolCount = toolCount
        self.type = type
    }

    enum CodingKeys: String, CodingKey {
        case auth = "auth"
        case enabled = "enabled"
        case error = "error"
        case name = "name"
        case status = "status"
        case toolCount = "tool_count"
        case type = "type"
    }
}

public struct Plan: Codable, Sendable, Equatable {
    public var architecture: String?
    public var context: String
    public var currentIdx: Int64
    public var files: [String]?
    public var name: String
    public var risks: String?
    public var tasks: [PlanTask]

    public init(architecture: String? = nil, context: String, currentIdx: Int64, files: [String]? = nil, name: String, risks: String? = nil, tasks: [PlanTask]) {
        self.architecture = architecture
        self.context = context
        self.currentIdx = currentIdx
        self.files = files
        self.name = name
        self.risks = risks
        self.tasks = tasks
    }

    enum CodingKeys: String, CodingKey {
        case architecture = "architecture"
        case context = "context"
        case currentIdx = "current_idx"
        case files = "files"
        case name = "name"
        case risks = "risks"
        case tasks = "tasks"
    }
}

public struct PlanTask: Codable, Sendable, Equatable {
    public var description: String
    public var id: Int64
    public var result: String?
    public var status: Int64
    public var substeps: [String]?
    public var title: String

    public init(description: String, id: Int64, result: String? = nil, status: Int64, substeps: [String]? = nil, title: String) {
        self.description = description
        self.id = id
        self.result = result
        self.status = status
        self.substeps = substeps
        self.title = title
    }

    enum CodingKeys: String, CodingKey {
        case description = "description"
        case id = "id"
        case result = "result"
        case status = "status"
        case substeps = "substeps"
        case title = "title"
    }
}

public struct QuestionDef: Codable, Sendable, Equatable {
    public var category: String
    public var id: String
    public var options: [String]?
    public var question: String

    public init(category: String, id: String, options: [String]? = nil, question: String) {
        self.category = category
        self.id = id
        self.options = options
        self.question = question
    }

    enum CodingKeys: String, CodingKey {
        case category = "category"
        case id = "id"
        case options = "options"
        case question = "question"
    }
}

public struct ReplayBlock: Codable, Sendable, Equatable {
    public var attempt: Int64?
    public var input: [String: JSONValue]?
    public var isError: Bool?
    public var kind: String
    public var maxRetries: Int64?
    public var output: String?
    public var stepId: String?
    public var text: String?
    public var toolId: String?
    public var toolName: String?
    public var waitSecs: Int64?

    public init(attempt: Int64? = nil, input: [String: JSONValue]? = nil, isError: Bool? = nil, kind: String, maxRetries: Int64? = nil, output: String? = nil, stepId: String? = nil, text: String? = nil, toolId: String? = nil, toolName: String? = nil, waitSecs: Int64? = nil) {
        self.attempt = attempt
        self.input = input
        self.isError = isError
        self.kind = kind
        self.maxRetries = maxRetries
        self.output = output
        self.stepId = stepId
        self.text = text
        self.toolId = toolId
        self.toolName = toolName
        self.waitSecs = waitSecs
    }

    enum CodingKeys: String, CodingKey {
        case attempt = "attempt"
        case input = "input"
        case isError = "is_error"
        case kind = "kind"
        case maxRetries = "max_retries"
        case output = "output"
        case stepId = "step_id"
        case text = "text"
        case toolId = "tool_id"
        case toolName = "tool_name"
        case waitSecs = "wait_secs"
    }
}

public struct ReplayMessage: Codable, Sendable, Equatable {
    public var blocks: [ReplayBlock]
    public var role: String
    public var timestamp: String?

    public init(blocks: [ReplayBlock], role: String, timestamp: String? = nil) {
        self.blocks = blocks
        self.role = role
        self.timestamp = timestamp
    }

    enum CodingKeys: String, CodingKey {
        case blocks = "blocks"
        case role = "role"
        case timestamp = "timestamp"
    }
}

public struct SkillInfo: Codable, Sendable, Equatable {
    public var description: String
    public var name: String

    public init(description: String, name: String) {
        self.description = description
        self.name = name
    }

    enum CodingKeys: String, CodingKey {
        case description = "description"
        case name = "name"
    }
}

public struct StepCost: Codable, Sendable, Equatable {
    public var cacheCreationTokens: Int64
    public var cacheReadTokens: Int64
    public var cost: Double
    public var durationMs: Int64?
    public var explanation: String?
    public var inputTokens: Int64
    public var model: String
    public var outputTokens: Int64
    public var stepId: String

    public init(cacheCreationTokens: Int64, cacheReadTokens: Int64, cost: Double, durationMs: Int64? = nil, explanation: String? = nil, inputTokens: Int64, model: String, outputTokens: Int64, stepId: String) {
        self.cacheCreationTokens = cacheCreationTokens
        self.cacheReadTokens = cacheReadTokens
        self.cost = cost
        self.durationMs = durationMs
        self.explanation = explanation
        self.inputTokens = inputTokens
        self.model = model
        self.outputTokens = outputTokens
        self.stepId = stepId
    }

    enum CodingKeys: String, CodingKey {
        case cacheCreationTokens = "cache_creation_tokens"
        case cacheReadTokens = "cache_read_tokens"
        case cost = "cost"
        case durationMs = "duration_ms"
        case explanation = "explanation"
        case inputTokens = "input_tokens"
        case model = "model"
        case outputTokens = "output_tokens"
        case stepId = "step_id"
    }
}

public struct ThreadCommand: Codable, Sendable, Equatable {
    public var authToken: String?
    public var data: JSONValue
    public var type: String

    public init(authToken: String? = nil, data: JSONValue, type: String) {
        self.authToken = authToken
        self.data = data
        self.type = type
    }

    enum CodingKeys: String, CodingKey {
        case authToken = "auth_token"
        case data = "data"
        case type = "type"
    }
}

public struct ThreadConfirmData: Codable, Sendable, Equatable {
    public var approved: Bool
    public var persistDirs: Bool?

    public init(approved: Bool, persistDirs: Bool? = nil) {
        self.approved = approved
        self.persistDirs = persistDirs
    }

    enum CodingKeys: String, CodingKey {
        case approved = "approved"
        case persistDirs = "persist_dirs"
    }
}

public struct ThreadEvent: Codable, Sendable, Equatable {
    public var data: JSONValue
    public var type: String

    public init(data: JSONValue, type: String) {
        self.data = data
        self.type = type
    }

    enum CodingKeys: String, CodingKey {
        case data = "data"
        case type = "type"
    }
}

public struct ThreadInputData: Codable, Sendable, Equatable {
    public var attachments: [Attachment]?
    public var text: String

    public init(attachments: [Attachment]? = nil, text: String) {
        self.attachments = attachments
        self.text = text
    }

    enum CodingKeys: String, CodingKey {
        case attachments = "attachments"
        case text = "text"
    }
}

public struct ThreadPlanActionData: Codable, Sendable, Equatable {
    public var action: String
    public var text: String?

    public init(action: String, text: String? = nil) {
        self.action = action
        self.text = text
    }

    enum CodingKeys: String, CodingKey {
        case action = "action"
        case text = "text"
    }
}

public struct ThreadRenameData: Codable, Sendable, Equatable {
    public var title: String

    public init(title: String) {
        self.title = title
    }

    enum CodingKeys: String, CodingKey {
        case title = "title"
    }
}

public struct ThreadSetModelData: Codable, Sendable, Equatable {
    public var model: String

    public init(model: String) {
        self.model = model
    }

    enum CodingKeys: String, CodingKey {
        case model = "model"
    }
}

public struct ThreadStartData: Codable, Sendable, Equatable {
    public var attachThreadId: String?
    public var clientVersion: String?
    public var configDir: String?
    public var cwd: String
    public var enableAutomaticDirectoryAccess: Bool
    public var enableAutomaticWritePermission: Bool
    public var forceInit: Bool
    public var forkThreadId: String?
    public var forkTurnIdx: Int64?
    public var headless: Bool
    public var model: String

    public init(attachThreadId: String? = nil, clientVersion: String? = nil, configDir: String? = nil, cwd: String, enableAutomaticDirectoryAccess: Bool, enableAutomaticWritePermission: Bool, forceInit: Bool, forkThreadId: String? = nil, forkTurnIdx: Int64? = nil, headless: Bool, model: String) {
        self.attachThreadId = attachThreadId
        self.clientVersion = clientVersion
        self.configDir = configDir
        self.cwd = cwd
        self.enableAutomaticDirectoryAccess = enableAutomaticDirectoryAccess
        self.enableAutomaticWritePermission = enableAutomaticWritePermission
        self.forceInit = forceInit
        self.forkThreadId = forkThreadId
        self.forkTurnIdx = forkTurnIdx
        self.headless = headless
        self.model = model
    }

    enum CodingKeys: String, CodingKey {
        case attachThreadId = "attach_thread_id"
        case clientVersion = "client_version"
        case configDir = "config_dir"
        case cwd = "cwd"
        case enableAutomaticDirectoryAccess = "enable_automatic_directory_access"
        case enableAutomaticWritePermission = "enable_automatic_write_permission"
        case forceInit = "force_init"
        case forkThreadId = "fork_thread_id"
        case forkTurnIdx = "fork_turn_idx"
        case headless = "headless"
        case model = "model"
    }
}

public struct ThreadSummary: Codable, Sendable, Equatable {
    public var attached: Bool?
    public var closed: Bool?
    public var cwd: String
    public var firstMessage: String?
    public var forkTurnIdx: Int64?
    public var id: String
    public var jobStatus: String?
    public var lastRequestAt: String?
    public var model: String
    public var origin: String?
    public var parentId: String?
    public var startedAt: String?
    public var title: String?
    public var trigger: TriggerInfo?
    public var unread: Bool?

    public init(attached: Bool? = nil, closed: Bool? = nil, cwd: String, firstMessage: String? = nil, forkTurnIdx: Int64? = nil, id: String, jobStatus: String? = nil, lastRequestAt: String? = nil, model: String, origin: String? = nil, parentId: String? = nil, startedAt: String? = nil, title: String? = nil, trigger: TriggerInfo? = nil, unread: Bool? = nil) {
        self.attached = attached
        self.closed = closed
        self.cwd = cwd
        self.firstMessage = firstMessage
        self.forkTurnIdx = forkTurnIdx
        self.id = id
        self.jobStatus = jobStatus
        self.lastRequestAt = lastRequestAt
        self.model = model
        self.origin = origin
        self.parentId = parentId
        self.startedAt = startedAt
        self.title = title
        self.trigger = trigger
        self.unread = unread
    }

    enum CodingKeys: String, CodingKey {
        case attached = "attached"
        case closed = "closed"
        case cwd = "cwd"
        case firstMessage = "first_message"
        case forkTurnIdx = "fork_turn_idx"
        case id = "id"
        case jobStatus = "job_status"
        case lastRequestAt = "last_request_at"
        case model = "model"
        case origin = "origin"
        case parentId = "parent_id"
        case startedAt = "started_at"
        case title = "title"
        case trigger = "trigger"
        case unread = "unread"
    }
}

public struct ThreadTrimData: Codable, Sendable, Equatable {
    public var turnIdx: Int64

    public init(turnIdx: Int64) {
        self.turnIdx = turnIdx
    }

    enum CodingKeys: String, CodingKey {
        case turnIdx = "turn_idx"
    }
}

public struct ThreadUserAnswerData: Codable, Sendable, Equatable {
    public var answer: String
    public var answers: [String: String]?
    public var text: String?

    public init(answer: String, answers: [String: String]? = nil, text: String? = nil) {
        self.answer = answer
        self.answers = answers
        self.text = text
    }

    enum CodingKeys: String, CodingKey {
        case answer = "answer"
        case answers = "answers"
        case text = "text"
    }
}

public struct ThreadWorkflowData: Codable, Sendable, Equatable {
    public var name: String
    public var text: String
    public var workflow: JSONValue?

    public init(name: String, text: String, workflow: JSONValue? = nil) {
        self.name = name
        self.text = text
        self.workflow = workflow
    }

    enum CodingKeys: String, CodingKey {
        case name = "name"
        case text = "text"
        case workflow = "workflow"
    }
}

public struct ThreadWorkflowMessageData: Codable, Sendable, Equatable {
    public var text: String

    public init(text: String) {
        self.text = text
    }

    enum CodingKeys: String, CodingKey {
        case text = "text"
    }
}

public struct TodoItem: Codable, Sendable, Equatable {
    public var content: String
    public var dependsOn: [String]?
    public var id: String
    public var status: String

    public init(content: String, dependsOn: [String]? = nil, id: String, status: String) {
        self.content = content
        self.dependsOn = dependsOn
        self.id = id
        self.status = status
    }

    enum CodingKeys: String, CodingKey {
        case content = "content"
        case dependsOn = "depends_on"
        case id = "id"
        case status = "status"
    }
}

public struct ToolStat: Codable, Sendable, Equatable {
    public var calls: Int64
    public var name: String
    public var summary: String

    public init(calls: Int64, name: String, summary: String) {
        self.calls = calls
        self.name = name
        self.summary = summary
    }

    enum CodingKeys: String, CodingKey {
        case calls = "calls"
        case name = "name"
        case summary = "summary"
    }
}

public struct TriggerInfo: Codable, Sendable, Equatable {
    public var ref: String?
    public var type: String

    public init(ref: String? = nil, type: String) {
        self.ref = ref
        self.type = type
    }

    enum CodingKeys: String, CodingKey {
        case ref = "ref"
        case type = "type"
    }
}

public struct WorkflowInfo: Codable, Sendable, Equatable {
    public var name: String

    public init(name: String) {
        self.name = name
    }

    enum CodingKeys: String, CodingKey {
        case name = "name"
    }
}

public struct WorkflowStepInfo: Codable, Sendable, Equatable {
    public var explanation: String?
    public var id: String

    public init(explanation: String? = nil, id: String) {
        self.explanation = explanation
        self.id = id
    }

    enum CodingKeys: String, CodingKey {
        case explanation = "explanation"
        case id = "id"
    }
}
