package daemon

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/get-vix/vix/internal/config"
	"github.com/get-vix/vix/internal/daemon/llm"
	"github.com/get-vix/vix/internal/protocol"
)

// threadRecordSchemaVersion is the on-disk format version. Bump it when the
// shape of threadRecord changes incompatibly so loaders can migrate or skip.
const threadRecordSchemaVersion = 1

// threadRecord is the persisted, serialization-stable representation of a
// thread. It is written under ~/.vix/threads/{open,closed}/<id>.json (or the
// override dir's threads/ in config-dir mode). It carries enough to both
// continue the conversation (messages, model, cwd, mode) and redisplay it in a
// freshly launched TUI (via replay), plus UI/telemetry niceties.
type threadRecord struct {
	SchemaVersion int    `json:"schema_version"`
	ID            string `json:"id"`
	CWD           string `json:"cwd"`
	Model         string `json:"model"`
	// Title is the display title shown in the Threads list. Generated by an
	// LLM summarization pass after a few turns (user threads) or set at
	// creation time (job runs). Empty = clients fall back to FirstMessage.
	Title string `json:"title,omitempty"`
	// TitleManual pins Title: set when the user renames the thread, it
	// suppresses the auto-titling pass on restore so a manual name is never
	// overwritten. Absent on legacy records (= not manual).
	TitleManual bool   `json:"title_manual,omitempty"`
	ParentID    string `json:"parent_id,omitempty"`
	ForkTurnIdx int    `json:"fork_turn_idx,omitempty"`

	// JSON tag kept as the legacy "session_mode" so records written before the
	// sessions→threads rename still decode after the one-time dir migration.
	ThreadMode     string `json:"session_mode"`
	ActiveWorkflow string `json:"active_workflow,omitempty"`

	// WorkflowRun is the resume snapshot of an interrupted workflow run
	// (cursor, step results, per-step agent conversations, budget). Nil when
	// no run is in flight; completed runs are cleared rather than archived.
	WorkflowRun *WorkflowRunState `json:"workflow_run,omitempty"`

	Messages   []llm.MessageParam  `json:"messages"`
	TodoList   []protocol.TodoItem `json:"todo_list,omitempty"`
	ActivePlan *protocol.Plan      `json:"active_plan,omitempty"`

	// RetryNotices are transient-error retry notices (overload, rate limit, …)
	// captured during a workflow run, persisted so a reopened thread replays
	// the same lines an interactive run shows live. Each is anchored to the
	// message it follows in Messages (AfterIdx; -1 = before all messages).
	RetryNotices []retryNoticeRecord `json:"retry_notices,omitempty"`

	// FailureNotices are terminal-failure notices captured when a workflow run
	// aborts (e.g. a preflight bash step exiting non-zero). Persisted so a
	// reopened thread — a scheduled job run in particular — shows why it failed
	// instead of an empty transcript. Anchored like RetryNotices.
	FailureNotices []failureNoticeRecord `json:"failure_notices,omitempty"`

	StartedAt     time.Time `json:"started_at"`
	LastRequestAt time.Time `json:"last_request_at,omitempty"`

	// Provenance: empty Origin = user-started; "vix" = daemon-initiated
	// (scheduled job run, synthetic alert). Trigger records what fired it.
	Origin  string                `json:"origin,omitempty"`
	Trigger *protocol.TriggerInfo `json:"trigger,omitempty"`
	// JobStatus is the finished run's status (ok | error | timeout) for
	// vix-initiated records; empty for user threads and synthetic alerts.
	JobStatus string `json:"job_status,omitempty"`
	// Unread is the thread-global "content the user hasn't seen" flag. Set
	// on turn/run completion, cleared by thread.mark_read. Absent on legacy
	// records (= read), keeping upgrades quiet.
	Unread bool `json:"unread,omitempty"`

	TotalInputTokens  int64 `json:"total_input_tokens,omitempty"`
	TotalOutputTokens int64 `json:"total_output_tokens,omitempty"`
	TotalCacheRead    int64 `json:"total_cache_read,omitempty"`
	TotalCacheWrite   int64 `json:"total_cache_write,omitempty"`
}

// retryNoticeRecord is one persisted transient-error retry notice, projected
// into event.replay as a "retry" block so a reopened workflow run shows the
// same "API overloaded — retrying …" line an interactive run renders live.
type retryNoticeRecord struct {
	// AfterIdx is the index in threadRecord.Messages this notice renders
	// after (-1 = before all messages).
	AfterIdx   int    `json:"after_idx"`
	Reason     string `json:"reason"`
	Attempt    int    `json:"attempt"`
	MaxRetries int    `json:"max_retries"`
	WaitSecs   int    `json:"wait_secs"`
}

// failureNoticeRecord is one persisted terminal-failure notice, projected into
// event.replay as an "error" block so a reopened thread shows why a workflow
// run aborted (the failing step and its captured output) rather than a blank
// transcript.
type failureNoticeRecord struct {
	// AfterIdx is the index in threadRecord.Messages this notice renders
	// after (-1 = before all messages).
	AfterIdx int `json:"after_idx"`
	// StepID is the workflow step that failed, when known.
	StepID string `json:"step_id,omitempty"`
	// Reason is the human-readable failure message (includes the failing
	// step and its captured output for bash steps).
	Reason string `json:"reason"`
}

// threadRecordPath returns the path of a record within dir, or "" when dir is
// empty (persistence disabled because no home/override directory is available).
func threadRecordPath(dir, id string) string {
	if dir == "" {
		return ""
	}
	return filepath.Join(dir, id+".json")
}

// saveThreadRecord atomically writes rec to the open/ directory. A no-op (nil)
// when persistence is disabled (Threads() empty). The write goes to a unique
// temp file in the same directory, then renames over the target so a crash mid
// write never leaves a truncated record.
func saveThreadRecord(paths config.VixPaths, rec threadRecord) error {
	dir := paths.ThreadsOpen()
	if dir == "" {
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	rec.SchemaVersion = threadRecordSchemaVersion
	data, err := json.MarshalIndent(rec, "", "  ")
	if err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, rec.ID+".*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return err
	}
	return os.Rename(tmpName, threadRecordPath(dir, rec.ID))
}

// loadOpenThreadRecord reads the record for id from the open/ directory. The
// bool reports whether a record was found. Records in closed/ are deliberately
// not consulted: attach (the only caller) must never resurrect a thread the
// user explicitly closed — e.g. a stale TUI reconnect racing a quit-time close
// would otherwise re-persist the just-archived record back into open/.
func loadOpenThreadRecord(paths config.VixPaths, id string) (threadRecord, bool, error) {
	p := threadRecordPath(paths.ThreadsOpen(), id)
	if p == "" {
		return threadRecord{}, false, nil
	}
	data, err := os.ReadFile(p)
	if err != nil {
		if os.IsNotExist(err) {
			return threadRecord{}, false, nil
		}
		return threadRecord{}, false, err
	}
	var rec threadRecord
	if err := json.Unmarshal(data, &rec); err != nil {
		return threadRecord{}, false, err
	}
	return rec, true, nil
}

// listOpenThreadRecords returns every parseable record in the open/ directory.
// Unreadable/corrupt files are skipped rather than failing the whole listing.
func listOpenThreadRecords(paths config.VixPaths) []threadRecord {
	out := listThreadRecordsIn(paths.ThreadsOpen())
	// Creation order (oldest first) so the TUI displays threads in the order
	// the user started them.
	sort.SliceStable(out, func(i, j int) bool {
		return out[i].StartedAt.Before(out[j].StartedAt)
	})
	return out
}

// loadClosedThreadRecord reads the record for id from the closed/ directory by
// path (no directory scan). The bool reports whether it was found. Used only to
// keep a closed fork ancestor visible in the Threads tab; attach never consults
// closed/ (see loadOpenThreadRecord).
func loadClosedThreadRecord(paths config.VixPaths, id string) (threadRecord, bool) {
	p := threadRecordPath(paths.ThreadsClosed(), id)
	if p == "" {
		return threadRecord{}, false
	}
	data, err := os.ReadFile(p)
	if err != nil {
		return threadRecord{}, false
	}
	var rec threadRecord
	if err := json.Unmarshal(data, &rec); err != nil {
		return threadRecord{}, false
	}
	return rec, true
}

// closedForkAncestors returns the closed/ records that an open record still
// points at through its ParentID chain: for every open record whose parent is
// not itself open, the chain is walked up through closed/ until it reaches an
// open record or a record that no longer exists. Each ancestor is returned once,
// in creation order, so the Threads tab can show a closed parent above the forks
// that were taken from it. Cheap: one file read per missing ancestor.
func closedForkAncestors(paths config.VixPaths, open []threadRecord) []threadRecord {
	present := make(map[string]bool, len(open))
	for _, r := range open {
		present[r.ID] = true
	}
	var out []threadRecord
	for _, r := range open {
		pid := r.ParentID
		for pid != "" && !present[pid] {
			rec, ok := loadClosedThreadRecord(paths, pid)
			if !ok {
				break
			}
			present[pid] = true
			out = append(out, rec)
			pid = rec.ParentID
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		return out[i].StartedAt.Before(out[j].StartedAt)
	})
	return out
}

// openForkChildren returns the open/ records that were forked from id. skip
// reports ids whose close is already in flight (they count as closed), so a
// batch close of a fork followed by its parent is not refused. Used to refuse
// closing a thread that still has open forks.
func openForkChildren(paths config.VixPaths, id string, skip func(childID string) bool) []threadRecord {
	var out []threadRecord
	for _, r := range listThreadRecordsIn(paths.ThreadsOpen()) {
		if r.ParentID != id || r.ID == id {
			continue
		}
		if skip != nil && skip(r.ID) {
			continue
		}
		out = append(out, r)
	}
	return out
}

// aggregateThreadDirs ranks the working directories used by open user
// threads. Vix-initiated records (job runs, synthetic alerts) are excluded:
// they run from the job's cwd, not a directory the user chose. Directories are
// ranked by thread count (desc), tiebroken by most-recent activity (desc) then
// path (asc) for determinism. The activity time per record is LastRequestAt
// when set, else StartedAt.
func aggregateThreadDirs(recs []threadRecord) []protocol.DirUsage {
	type agg struct {
		count int
		last  time.Time
	}
	byDir := map[string]*agg{}
	for _, r := range recs {
		if r.Origin == "vix" || strings.TrimSpace(r.CWD) == "" {
			continue
		}
		act := r.LastRequestAt
		if act.IsZero() {
			act = r.StartedAt
		}
		a := byDir[r.CWD]
		if a == nil {
			a = &agg{}
			byDir[r.CWD] = a
		}
		a.count++
		if act.After(a.last) {
			a.last = act
		}
	}

	out := make([]protocol.DirUsage, 0, len(byDir))
	for path, a := range byDir {
		d := protocol.DirUsage{Path: path, Count: a.count}
		if !a.last.IsZero() {
			d.LastRequestAt = a.last.Format(time.RFC3339)
		}
		out = append(out, d)
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Count != out[j].Count {
			return out[i].Count > out[j].Count
		}
		if out[i].LastRequestAt != out[j].LastRequestAt {
			return out[i].LastRequestAt > out[j].LastRequestAt
		}
		return out[i].Path < out[j].Path
	})
	return out
}

// listThreadRecordsIn reads every parseable record in dir. Unreadable or
// corrupt files are skipped.
func listThreadRecordsIn(dir string) []threadRecord {
	if dir == "" {
		return nil
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	var out []threadRecord
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		var rec threadRecord
		if err := json.Unmarshal(data, &rec); err != nil {
			continue
		}
		out = append(out, rec)
	}
	return out
}

// Job-run retention defaults: open/ keeps the newest few runs per job (the
// "latest runs at a glance" view), closed/ keeps a deeper history.
const (
	jobRunsOpenKeep   = 3
	jobRunsClosedKeep = 10
)

// sweepJobRunRecords enforces per-job retention after a run persists.
// open/: the newest jobRunsOpenKeep vix-initiated records for jobRef stay;
// older successful ones are auto-dismissed to closed/. Failed runs (job_status
// error/timeout) and synthetic alerts (no job_status) are exempt — a failure
// never slides out of sight on its own; only the user dismisses it.
// closed/: the newest jobRunsClosedKeep records for jobRef stay; older ones
// are deleted. This doubles as the job's run history depth.
func sweepJobRunRecords(paths config.VixPaths, jobRef string) {
	forJob := func(recs []threadRecord) []threadRecord {
		var out []threadRecord
		for _, r := range recs {
			if r.Origin == "vix" && r.Trigger != nil && r.Trigger.Ref == jobRef {
				out = append(out, r)
			}
		}
		// Newest first.
		sort.SliceStable(out, func(i, j int) bool {
			return out[i].StartedAt.After(out[j].StartedAt)
		})
		return out
	}

	open := forJob(listThreadRecordsIn(paths.ThreadsOpen()))
	if len(open) > jobRunsOpenKeep {
		for _, r := range open[jobRunsOpenKeep:] {
			// Failures, alerts, and anything the user hasn't seen yet wait
			// for an explicit dismissal; only read, successful runs age out.
			if r.JobStatus != StatusOKRecord || r.Unread {
				continue
			}
			if err := moveThreadToClosed(paths, r.ID); err != nil {
				LogError("job retention: move %s to closed: %v", r.ID, err)
			}
		}
	}

	closed := forJob(listThreadRecordsIn(paths.ThreadsClosed()))
	if len(closed) > jobRunsClosedKeep {
		for _, r := range closed[jobRunsClosedKeep:] {
			p := threadRecordPath(paths.ThreadsClosed(), r.ID)
			if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
				LogError("job retention: delete %s: %v", r.ID, err)
			}
		}
	}
}

// StatusOKRecord is the job_status value marking a successful run record.
const StatusOKRecord = "ok"

// moveThreadToClosed moves a record from open/ to closed/. It is invoked on an
// explicit user close (the "x" action), never on a bare disconnect. A no-op
// when persistence is disabled or the open record does not exist.
func moveThreadToClosed(paths config.VixPaths, id string) error {
	src := threadRecordPath(paths.ThreadsOpen(), id)
	dst := threadRecordPath(paths.ThreadsClosed(), id)
	if src == "" || dst == "" {
		return nil
	}
	if _, err := os.Stat(src); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	return os.Rename(src, dst)
}

// deleteThreadRecord removes the record for id from both open/ and closed/.
// Used when an empty conversation is closed: there is nothing worth archiving,
// so the record is deleted instead of moved to closed/. A no-op when
// persistence is disabled or the files do not exist.
func deleteThreadRecord(paths config.VixPaths, id string) error {
	for _, dir := range []string{paths.ThreadsOpen(), paths.ThreadsClosed()} {
		p := threadRecordPath(dir, id)
		if p == "" {
			continue
		}
		if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	return nil
}

// migrateLegacyThreadsDir performs the one-time rename of the pre-rename
// sessions/ store to threads/. It runs at daemon startup, before the store is
// first read. Best effort and idempotent: a no-op when persistence is disabled,
// when threads/ already exists (migration already done, or a fresh install), or
// when there is no legacy sessions/ to move. Records inside are moved verbatim —
// their JSON keeps the legacy "session_mode" tag, which the loader still reads.
func migrateLegacyThreadsDir(paths config.VixPaths) {
	dst := paths.Threads()
	src := paths.LegacyThreads()
	if dst == "" || src == "" {
		return
	}
	if _, err := os.Stat(dst); err == nil {
		return // threads/ already present — nothing to migrate
	}
	if _, err := os.Stat(src); err != nil {
		return // no legacy sessions/ dir
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		LogError("migrate sessions/ -> threads/: mkdir parent: %v", err)
		return
	}
	if err := os.Rename(src, dst); err != nil {
		LogError("migrate sessions/ -> threads/: %v", err)
		return
	}
	LogInfo("migrated legacy sessions/ store to threads/ (%s -> %s)", src, dst)
}

// trimStaleClosedThreads deletes closed thread records whose last activity
// is older than maxAge. Last activity is the record's LastRequestAt, else
// StartedAt; unparsable/corrupt files fall back to their mtime so they don't
// accumulate forever. A no-op when maxAge <= 0 (retention disabled, the
// "never" setting) or persistence is unavailable. Run once at daemon startup.
func trimStaleClosedThreads(paths config.VixPaths, maxAge time.Duration) {
	if maxAge <= 0 {
		return
	}
	dir := paths.ThreadsClosed()
	if dir == "" {
		return
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}
	cutoff := time.Now().Add(-maxAge)
	trimmed := 0
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		p := filepath.Join(dir, e.Name())
		var last time.Time
		data, err := os.ReadFile(p)
		if err == nil {
			var rec threadRecord
			if json.Unmarshal(data, &rec) == nil {
				last = rec.lastActivity()
			}
		}
		if last.IsZero() {
			info, err := e.Info()
			if err != nil {
				continue
			}
			last = info.ModTime()
		}
		if last.After(cutoff) {
			continue
		}
		if err := os.Remove(p); err != nil {
			LogError("trim closed thread %s: %v", e.Name(), err)
			continue
		}
		trimmed++
	}
	if trimmed > 0 {
		LogInfo("trimmed %d stale closed thread(s) older than %s", trimmed, maxAge)
	}
}

// lastActivity returns the timestamp used to order the open list: the last
// request time if present, else the start time.
func (r threadRecord) lastActivity() time.Time {
	if !r.LastRequestAt.IsZero() {
		return r.LastRequestAt
	}
	return r.StartedAt
}

// firstUserMessage returns a short single-line preview of the first user text
// block, used for the Threads list "first message" column.
func (r threadRecord) firstUserMessage() string {
	for _, m := range r.Messages {
		if m.Role != llm.RoleUser {
			continue
		}
		for _, b := range m.Content {
			if b.Type == llm.BlockText && strings.TrimSpace(b.Text) != "" {
				return firstLine(b.Text)
			}
		}
	}
	return ""
}

// firstLine trims s to its first non-empty line, capped at 120 runes.
func firstLine(s string) string {
	s = strings.TrimSpace(s)
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		s = s[:i]
	}
	r := []rune(s)
	if len(r) > 120 {
		return string(r[:120]) + "…"
	}
	return s
}

// summary projects a record into the lightweight shape sent to the TUI for the
// thread.list response.
func (r threadRecord) summary() protocol.ThreadSummary {
	s := protocol.ThreadSummary{
		ID:           r.ID,
		CWD:          r.CWD,
		Model:        r.Model,
		Title:        r.Title,
		FirstMessage: r.firstUserMessage(),
		Origin:       r.Origin,
		Trigger:      r.Trigger,
		JobStatus:    r.JobStatus,
		Unread:       r.Unread,
		ParentID:     r.ParentID,
		ForkTurnIdx:  r.ForkTurnIdx,
	}
	if !r.StartedAt.IsZero() {
		s.StartedAt = r.StartedAt.Format(time.RFC3339)
	}
	if !r.LastRequestAt.IsZero() {
		s.LastRequestAt = r.LastRequestAt.Format(time.RFC3339)
	}
	return s
}

// buildRecord snapshots the thread's current state into a serializable record.
// Each piece is read under the lock that guards it.
func (s *Thread) buildRecord() threadRecord {
	s.mu.Lock()
	msgs := make([]llm.MessageParam, len(s.messages))
	copy(msgs, s.messages)
	notices := make([]retryNoticeRecord, len(s.retryNotices))
	copy(notices, s.retryNotices)
	failures := make([]failureNoticeRecord, len(s.failureNotices))
	copy(failures, s.failureNotices)
	plan := s.activePlan
	workflowRun := s.workflowRunState
	title := s.title
	titleManual := s.titleManual
	s.mu.Unlock()

	s.todoMu.RLock()
	todos := make([]protocol.TodoItem, len(s.todoList))
	copy(todos, s.todoList)
	s.todoMu.RUnlock()

	return threadRecord{
		ID:                s.id,
		CWD:               s.cwd,
		Model:             s.model,
		Title:             title,
		TitleManual:       titleManual,
		ParentID:          s.parentID,
		ForkTurnIdx:       s.forkTurnIdx,
		ThreadMode:        s.threadMode,
		ActiveWorkflow:    s.activeWorkflow,
		WorkflowRun:       workflowRun,
		Messages:          msgs,
		TodoList:          todos,
		ActivePlan:        plan,
		RetryNotices:      notices,
		FailureNotices:    failures,
		StartedAt:         s.startTime,
		LastRequestAt:     s.lastRequestAt,
		Origin:            s.origin,
		Trigger:           s.trigger,
		JobStatus:         s.jobStatus,
		Unread:            s.unread,
		TotalInputTokens:  s.totalInputTokens,
		TotalOutputTokens: s.totalOutputTokens,
		TotalCacheRead:    s.totalCacheRead,
		TotalCacheWrite:   s.totalCacheWrite,
	}
}

// persist writes the thread's current state to the open/ directory. Best
// effort: failures are logged, never surfaced to the user. No-op when
// persistence is disabled (no home/override dir) or the thread was closed by
// the user (its record now lives in closed/ and must not be resurrected).
func (s *Thread) persist() {
	if s.paths.ThreadsOpen() == "" || s.closedByUser {
		return
	}
	if err := saveThreadRecord(s.paths, s.buildRecord()); err != nil {
		LogError("persist thread %s: %v", s.id, err)
	}
}

// seedFromRecord restores conversation state from a persisted record onto a
// freshly constructed thread (used by the attach path). It does NOT restore
// the model — attach deliberately resumes on the current default and warns on
// mismatch in finalizeReplay.
func (s *Thread) seedFromRecord(rec *threadRecord) {
	s.messages = append([]llm.MessageParam(nil), rec.Messages...)
	// Rebuild the read-gate set from history: persistence carries messages but
	// not the in-memory readFiles map, so without this a resumed thread would
	// block edits on files the prior thread had already read.
	s.rebuildReadFilesFromHistory(s.messages)
	// Rebuild the per-turn fork snapshots from the restored history so an
	// attached/restored thread can itself be duplicated or trimmed (both read
	// turnSnapshots, which persistence doesn't carry).
	s.turnSnapshots = rebuildTurnSnapshots(s.messages)
	s.retryNotices = append([]retryNoticeRecord(nil), rec.RetryNotices...)
	s.failureNotices = append([]failureNoticeRecord(nil), rec.FailureNotices...)
	s.todoList = append([]protocol.TodoItem(nil), rec.TodoList...)
	s.activePlan = rec.ActivePlan
	s.title = rec.Title
	s.titleManual = rec.TitleManual
	// Rebuild the end-turn counter that drives auto-titling: each assistant
	// message without tool calls corresponds to one end_turn stop.
	s.endTurnCount = countEndTurns(s.messages)
	s.parentID = rec.ParentID
	s.forkTurnIdx = rec.ForkTurnIdx
	s.origin = rec.Origin
	s.trigger = rec.Trigger
	s.jobStatus = rec.JobStatus
	s.unread = rec.Unread
	s.threadMode = rec.ThreadMode
	if s.threadMode == "" {
		s.threadMode = "chat"
	}
	s.activeWorkflow = rec.ActiveWorkflow
	// An interrupted run persisted as "running" means the daemon died
	// mid-workflow; park it as paused so it reads correctly and resumes the
	// same way as a user-cancelled run.
	if rec.WorkflowRun != nil && rec.WorkflowRun.Status == WorkflowStatusRunning {
		rec.WorkflowRun.Status = WorkflowStatusPaused
	}
	s.workflowRunState = rec.WorkflowRun
	if !rec.StartedAt.IsZero() {
		s.startTime = rec.StartedAt
	}
	s.lastRequestAt = rec.LastRequestAt
	s.totalInputTokens = rec.TotalInputTokens
	s.totalOutputTokens = rec.TotalOutputTokens
	s.totalCacheRead = rec.TotalCacheRead
	s.totalCacheWrite = rec.TotalCacheWrite
	s.attachRecord = rec
}

// emitReplay rebuilds the client's chat viewport for an attached thread with a
// content-only replay, emitted BEFORE initBrain runs so the on-disk transcript
// renders immediately (no network wait). It marks the replay Initializing so
// the client shows the conversation read-only until finalizeReplay unlocks it.
//
// It deliberately does NOT clear s.attachRecord or compute restore warnings —
// those depend on initBrain (s.model, s.workflows) and are handled by
// finalizeReplay via event.replay_ready. It DOES carry the saved rec.Model so
// the client can reconstruct turn separators (which key off a non-empty model)
// and thus keep the restored transcript forkable/trimmable/duplicable; any
// model fallback is reconciled later by event.replay_ready.
func (s *Thread) emitReplay() {
	rec := s.attachRecord
	if rec == nil {
		return
	}

	s.mu.Lock()
	msgs := make([]llm.MessageParam, len(s.messages))
	copy(msgs, s.messages)
	notices := make([]retryNoticeRecord, len(s.retryNotices))
	copy(notices, s.retryNotices)
	failures := make([]failureNoticeRecord, len(s.failureNotices))
	copy(failures, s.failureNotices)
	plan := s.activePlan
	title := s.title
	mode := s.threadMode
	workflow := s.activeWorkflow
	s.mu.Unlock()

	s.todoMu.RLock()
	todos := make([]protocol.TodoItem, len(s.todoList))
	copy(todos, s.todoList)
	s.todoMu.RUnlock()

	s.emit("event.replay", protocol.EventReplay{
		Messages:       buildReplayMessages(msgs, notices, failures),
		Todos:          todos,
		ActivePlan:     plan,
		Model:          rec.Model,
		Title:          title,
		ThreadMode:     mode,
		ActiveWorkflow: workflow,
		Initializing:   true,
	})
}

// finalizeReplay runs after initBrain, when s.model and s.workflows are
// resolved. It applies restore-time validation (model changed, workflow
// missing), clears s.attachRecord, persists any fallback, and emits
// event.replay_ready so the client unlocks input (drops the read-only state)
// and renders the warnings. No-op for a non-attached (fresh) thread.
func (s *Thread) finalizeReplay() {
	rec := s.attachRecord
	if rec == nil {
		return
	}
	s.attachRecord = nil

	var warnings []string

	// Model: attach resumes on the current default (s.model, resolved by
	// initBrain). Warn if the saved model differed.
	if rec.Model != "" && rec.Model != s.model {
		warnings = append(warnings, fmt.Sprintf("This conversation was saved with model %q; switched to your current default %q.", rec.Model, s.model))
	}

	// Workflow: if the saved workflow no longer exists, fall back to chat mode.
	if s.threadMode == "workflow" && s.activeWorkflow != "" {
		found := false
		for _, w := range s.snapshotWorkflows() {
			if w.Name == s.activeWorkflow {
				found = true
				break
			}
		}
		if !found {
			warnings = append(warnings, fmt.Sprintf("Workflow %q no longer exists; this thread has been switched to chat mode.", s.activeWorkflow))
			s.threadMode = "chat"
			s.activeWorkflow = ""
			s.setWorkflowRunState(nil)
		}
	}

	// Interrupted workflow run: offer to pick it up from its cursor. Sending
	// any message while this workflow is active dispatches thread.workflow,
	// which detects the saved state and resumes instead of restarting.
	if st := s.snapshotWorkflowRunState(); st != nil && st.Resumable() && s.activeWorkflow == st.Name {
		warnings = append(warnings, fmt.Sprintf(
			"Workflow %q was interrupted at step '%s' (iteration %d). Send a message to resume it, or /clear to discard the run.",
			st.Name, st.CurrentRef.ID, st.Iteration))
	}

	s.emit("event.replay_ready", protocol.EventReplayReady{
		Model:          s.model,
		ThreadMode:     s.threadMode,
		ActiveWorkflow: s.activeWorkflow,
		Warnings:       warnings,
	})

	// Persist any fallback (mode/model) so the on-disk record reflects reality.
	s.persist()
}

// buildReplayMessages projects llm history into the wire-stable replay shape,
// interleaving any retry and failure notices at the position they were anchored
// to (so a reopened workflow run shows the same "API overloaded — retrying …"
// lines an interactive run renders live, and any terminal failure that aborted
// the run). Empty assistant/user messages (no renderable blocks) are skipped,
// but notices anchored to them are still emitted.
func buildReplayMessages(msgs []llm.MessageParam, notices []retryNoticeRecord, failures []failureNoticeRecord) []protocol.ReplayMessage {
	out := make([]protocol.ReplayMessage, 0, len(msgs)+len(notices)+len(failures))
	emitNotices := func(afterIdx int) {
		for _, n := range notices {
			if n.AfterIdx != afterIdx {
				continue
			}
			out = append(out, protocol.ReplayMessage{
				Role: "system",
				Blocks: []protocol.ReplayBlock{{
					Kind:       "retry",
					Text:       n.Reason,
					Attempt:    n.Attempt,
					MaxRetries: n.MaxRetries,
					WaitSecs:   n.WaitSecs,
				}},
			})
		}
		for _, f := range failures {
			if f.AfterIdx != afterIdx {
				continue
			}
			out = append(out, protocol.ReplayMessage{
				Role: "system",
				Blocks: []protocol.ReplayBlock{{
					Kind:   "error",
					Text:   f.Reason,
					StepID: f.StepID,
				}},
			})
		}
	}
	emitNotices(-1) // notices anchored before any message
	for i, m := range msgs {
		rm := protocol.ReplayMessage{Role: string(m.Role)}
		if !m.Timestamp.IsZero() {
			rm.Timestamp = m.Timestamp.Format(time.RFC3339)
		}
		for _, b := range m.Content {
			switch b.Type {
			case llm.BlockText:
				if strings.TrimSpace(b.Text) == "" {
					continue
				}
				rm.Blocks = append(rm.Blocks, protocol.ReplayBlock{Kind: "text", Text: b.Text})
			case llm.BlockThinking:
				if strings.TrimSpace(b.Text) == "" {
					continue
				}
				rm.Blocks = append(rm.Blocks, protocol.ReplayBlock{Kind: "thinking", Text: b.Text})
			case llm.BlockToolUse:
				rm.Blocks = append(rm.Blocks, protocol.ReplayBlock{
					Kind:     "tool_use",
					ToolID:   b.ID,
					ToolName: b.Name,
					Input:    b.Input,
				})
			case llm.BlockToolResult:
				rm.Blocks = append(rm.Blocks, protocol.ReplayBlock{
					Kind:    "tool_result",
					ToolID:  b.ToolUseID,
					Output:  b.Output,
					IsError: b.IsError,
				})
			}
		}
		if len(rm.Blocks) > 0 {
			out = append(out, rm)
		}
		emitNotices(i)
	}
	return out
}
